services:
  mariadb:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: BestPasswordEver:)
    volumes:
      - ./DB/db:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
